Label in todo
codingstart0/best_practise pull request #36
Opened 2024-11-21 20:30 UTC by codingstart0

Done // TODO: Label sugeneruoti per atskira fn ir prideti i li struktura
Done // TODO: perpanaudoti label generavimo fn ir cia.

2024-11-21 20:58 UTC, gegis commented on toDoApp/script.js
> +  return label;
cia su laiku bus visokie code linting su taisyklem, bet gera taisykle isskirti return, extra nauja tuscia eilute pries return statement.

2024-11-21 21:00 UTC, gegis commented on toDoApp/script.js
> +  // TODO: Label sugeneruoti per atskira fn ir prideti i li struktura
cia dar sitas TODO planuojamas dabar padaryt?

2024-11-21 21:01 UTC, gegis commented on toDoApp/script.js
>          <div class="form-check">
cia sita klase bootstrapui reikalinga? ir tai reiskia kad cia turejo but tik checkbox wrapper?

2024-11-21 21:03 UTC, gegis commented on toDoApp/script.js
> +      // TODO: perpanaudoti label generavimo fn ir cia
cia sito TODO dar reikia?

2024-11-21 21:04 UTC, gegis commented on toDoApp/script.js
> +  todos = todos.map((todoItem) => {
cia gal sagiau i nauja const pasidaryt tada ji issaugot i local storage ir tada perrasyt global todos.
```
const updatedTodos = todos.map.....
saveTodoToLocalStorage(updatedTodos);
todos = updatedTodos;

2024-11-21 21:07 UTC, gegis commented on toDoApp/script.js
> +  li.onchange = toggleComplete.bind(this, todo.id);
cia klausimas ar ant `li` change mes norim toggle, ne ant checkbox?

2024-11-21 21:09 UTC, gegis requested changes
Pakomentavau, paprasysiu changes (cia keistai github, kad praso komentara dar kazkoki palikt, norin Request Changes, nes siaip ant kodo pakomentuoji, nebutina dazniausiai dar vieno komentaro nori request changes/ approve)

2024-11-21 22:01 UTC, codingstart0 commented on toDoApp/script.js
> +  // TODO: Label sugeneruoti per atskira fn ir prideti i li struktura
Ai ne cia jau padaryta tik dar coment nenutryniau.

2024-11-21 22:12 UTC, codingstart0 commented on toDoApp/script.js
> +  return label;
Pretier taip suprantu šitų dalykų nepadaro. Ar čia settingsų reik susistatyti?

2024-11-23 07:18 UTC, codingstart0 commented on toDoApp/script.js
> +  li.onchange = toggleComplete.bind(this, todo.id);
šita perdariau, kad event listener būtų ant checkbox

2024-11-23 07:33 UTC, codingstart0 commented on toDoApp/script.js
> +      // TODO: perpanaudoti label generavimo fn ir cia
OK, supratau keliant į PR jau turi likti gražus galutinis variantas, be jokių nereikalingų ar laikinų komentarų. Nes gi viskas merginasi į MAINa.

2024-11-23 07:34 UTC, codingstart0 commented on toDoApp/script.js
>          <div class="form-check">
Čia šitos vietos nepagaunu..

2024-11-24 09:53 UTC, codingstart0 reviewed
Atsakiau į tavo komentus gitHub ir pataisiau kodą per vscode, tada git push padariau.

Tik klausimas ar taip reik daryti ar tiesiai github kažkaip pataisyti. Ten kai rodydavai pas save per bitbucket, tai konfliktus vietoj praspresdavai negrįždamas į IDE.

Tai dbr dar bandau suprasti kaip įgyvendinti ta request changes, kad git hub suprastu, jog new nupushintas kodas tam ir skirtas? Ar čia jau automatiškai jis pagaus kas kaip nes tas pats branch.

Man tik comment optionas leidžiamas
![Screenshot from 2024-11-24 11-52-51](https://github.com/user-attachments/assets/d54897f2-c66e-4609-8cfb-ce446bae71b8)

2024-11-27 06:42 UTC, gegis commented on toDoApp/script.js
>    const li = button.closest('li'); // Get the parent todo item
cia vis dar negerai ima pagal DOM struktura, reiktu pagal ID

2024-11-27 06:43 UTC, gegis commented on toDoApp/script.js
>      li.remove();
cia reiktu pagalvot perpanaudot `removeTodo` funkcija

2024-11-27 09:16 UTC, gegis approved these changes
Looks good

2024-11-27 09:19 UTC, merged